In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv('/content/hospital_readmission.csv')

In [ ]:
df.shape

(32300, 10)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32300 entries, 0 to 32299
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  31653 non-null  object
 1   length_of_stay_days  31652 non-null  float64
 2   num_diagnoses        31655 non-null  float64
 3   num_medications      31654 non-null  float64
 4   prev_admissions      31654 non-null  float64
 5   glucose_level        31654 non-null  float64
 6   bmi                  31654 non-null  float64
 7   has_diabetes         31653 non-null  float64
 8   discharge_type       31655 non-null  float64
 9   readmitted_30days    32300 non-null  int64
dtypes: float64(8), int64(1), object(1)
memory usage: 2.5+ MB

In [ ]:
numeric_col = ['length_of_stay_days','num_diagnoses','num_medications',
               'prev_admissions','glucose_level','bmi','has_diabetes','discharge_type']

In [ ]:
df[numeric_col] = df[numeric_col].fillna(df[numeric_col].median())
df['age'] = df['age'].fillna(df['age'].mode()[0])

In [ ]:
df.isnull().sum()

age                    0
length_of_stay_days    0
num_diagnoses          0
num_medications        0
prev_admissions        0
glucose_level          0
bmi                    0
has_diabetes           0
discharge_type         0
readmitted_30days      0
dtype: int64

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.shape

(32002, 129)

In [ ]:
df = pd.get_dummies(df,columns=['age'],drop_first = True)

In [ ]:
df = df.astype(int)

In [ ]:
df.head()

,length_of_stay_days,num_diagnoses,num_medications,prev_admissions,glucose_level,bmi,has_diabetes,discharge_type,readmitted_30days,age_18.0,...,age_85.0,age_85.0_err,age_86.0,age_87.0,age_87.0_err,age_88.0,age_88.0_err,age_89.0,age_89.0_err,age_nan_err
0,28,2,13,4,89,48,1,2,0,0,...,0,0,0,0,0,0,0,0,0,0
1,12,7,11,2,254,23,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,15,9,16,6,270,16,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
3,15,5,16,6,208,18,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,24,1,6,6,233,44,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
x = df.drop(columns=['readmitted_30days'],axis=1)
y = df['readmitted_30days']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
col = ['length_of_stay_days','num_diagnoses','num_medications','prev_admissions','glucose_level','bmi']
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
df = df.astype(int)

In [ ]:
df.head()

,length_of_stay_days,num_diagnoses,num_medications,prev_admissions,glucose_level,bmi,has_diabetes,discharge_type,readmitted_30days,age_18.0,...,age_85.0,age_85.0_err,age_86.0,age_87.0,age_87.0_err,age_88.0,age_88.0_err,age_89.0,age_89.0_err,age_nan_err
0,1,-1,0,0,-1,1,1,2,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,1,0,1,-1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,0,-1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,1,-1,0,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(penalty='l2',C=0.1,max_iter=1000)
model.fit(x_train,y_train)
y_pred = model.predict(x_test)

In [ ]:
y_prob = model.predict_proba(x_test)[:,1]

In [ ]:
from sklearn.metrics import roc_auc_score,confusion_matrix,accuracy_score,classification_report
auc = roc_auc_score(y_test,y_prob)
print("ROC-AUC : ",auc)

ROC-AUC :  0.8723594813240214

In [ ]:
print("Confusion Matrix : ")
print(confusion_matrix(y_test,y_pred))

Confusion Matrix :
[[2520  674]
 [ 712 2495]]

In [ ]:
print("Classification Matrix : ")
print(classification_report(y_test,y_pred))

Classification Matrix :
              precision    recall  f1-score   support

           0       0.78      0.79      0.78      3194
           1       0.79      0.78      0.78      3207

    accuracy                           0.78      6401
   macro avg       0.78      0.78      0.78      6401
weighted avg       0.78      0.78      0.78      6401